// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Wg8ONN3KQkpFj7YswbxlXFckpokqIsA',
    appId: '1:508331189480:web:52ec100298779384a3555d',
    messagingSenderId: '508331189480',
    projectId: 'chatapp-firebase-7b4ab',
    authDomain: 'chatapp-firebase-7b4ab.firebaseapp.com',
    storageBucket: 'chatapp-firebase-7b4ab.appspot.com',
    measurementId: 'G-014G7VF3XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2V82Czve-BmU1SGvTxcDM7x8V9SATYk',
    appId: '1:508331189480:android:6684d423df8fadc0a3555d',
    messagingSenderId: '508331189480',
    projectId: 'chatapp-firebase-7b4ab',
    storageBucket: 'chatapp-firebase-7b4ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_5sAwqrtUaeA4PuiwELaXBZBq2d9bxI',
    appId: '1:508331189480:ios:4570121fac59558da3555d',
    messagingSenderId: '508331189480',
    projectId: 'chatapp-firebase-7b4ab',
    storageBucket: 'chatapp-firebase-7b4ab.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_5sAwqrtUaeA4PuiwELaXBZBq2d9bxI',
    appId: '1:508331189480:ios:4570121fac59558da3555d',
    messagingSenderId: '508331189480',
    projectId: 'chatapp-firebase-7b4ab',
    storageBucket: 'chatapp-firebase-7b4ab.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Wg8ONN3KQkpFj7YswbxlXFckpokqIsA',
    appId: '1:508331189480:web:23c2f73ff413afeda3555d',
    messagingSenderId: '508331189480',
    projectId: 'chatapp-firebase-7b4ab',
    authDomain: 'chatapp-firebase-7b4ab.firebaseapp.com',
    storageBucket: 'chatapp-firebase-7b4ab.appspot.com',
    measurementId: 'G-29JBMKBH72',
  );
}
